from dnn101.pinns.pde_domain import PDEDomain, PDEDomainEllipse, PDEDomainBox
from dnn101.pinns.poisson import DNN101DataPINNPoisson2D, pde_libraryPoisson2D, PoissonEquation2DPINN
from dnn101.pinns.heat_equation import DNN101DataPINNHeatEquation1D, pde_libraryHeatEquation1D, HeatEquation1DPINN
from dnn101.pinns.wave_equation import DNN101DataPINNWaveEquation1D, WaveEquationPINN
