from dnn101.pinns.pde_domain import PDEDomain, PDEDomainEllipse, PDEDomainBox
from dnn101.pinns.pde_data import DNN101DataPINN
from dnn101.pinns.poisson import DNN101DataPINNPoisson2D, PoissonEquation2DPINN, pde_library_Poisson2D
from dnn101.pinns.heat_equation import DNN101DataPINNHeatEquation1D, HeatEquation1DPINN, pde_library_HeatEquation1D
from dnn101.pinns.wave_equation import DNN101DataPINNWaveEquation1D, WaveEquationPINN
from dnn101.pinns.burgers_equation import DNN101DataPINNBurgersEquation1D, BurgersEquation1DPINN, pde_library_BurgersEquation1D


